// TODO: this page should be editable by an administrator and display the user data to unautherized users.
// shoould ignogre the leauge prev picked and display all player data to unautherized users and be editable if amdmin is signed in.
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from 'next/router';
import Link from 'next/link';
import { GetServerSideProps } from 'next'
import { useEffect, useState } from "react";


type Data = { 
  id:number;
  name:string;
 }

const playerHome: NextPage = (props) => {
  const router = useRouter()
  const playerId = router.query.id
  const playerName = router.query.name
  const currentLeagueName = router.query.leagueName
  const currentLeagueId = router.query.leagueId
  const [player,setPlayer] = useState({
    id:-1,
    name:'-1',
    handicap:-1,
    teamId:-1,
  })
    
    //call to db for player info. TODO: optimize db for less calls
  useEffect(()=>{
    if (playerId != undefined){
      fetch(`/api/playerSearch/player/${playerId}`)
      .then((res)  =>  
        res.json()
      )
      .then(async(data) =>{ 
        setPlayer(await data.player)
      },);  
      }
  },[playerName])
  if (!player) {
    return <h1>Sorry we had a problem finding that player</h1>
  }
  //TODO: this page should display player information and profile data
  return (
    <>
    <Head>
    <title> {playerName}</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main>
        <h1 className=" sm:m-2 sm:text-xl sm:flex sm:justify-center"> {playerName}</h1>
        <div className="sm:h-1/2 sm:w-12/12 sm:flex sm:justify-center">
                <div className="sm:flex sm:justify-center">
                  <img src="" alt="" />
                  <p>{player['handicap']}</p>
                  <p>{player['name']}</p>
                </div>            
          
           
           </div>

  </main>
        </>
  )
}

export default playerHome;