import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";



const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Golf League Beta</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1 className="sm:text-4xl sm:flex sm:justify-center">Correy is gay</h1>
        <div className="sm:flex sm:justify-center">
          <form action="">
            <label htmlFor="">
              League ID
            </label>
            <input type="text" className="border p-2 m-2" />
            <button className="border p-2">Search</button>
          </form>
        </div>
      </main>
    </>
  );
};

export default Home;
