import { type NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import Link from 'next/link';
import { GetServerSideProps } from 'next'

type Data = { 
  id:number;
  name:string;
 }

export const getServerSideProps: GetServerSideProps<{ data: Data }> = async (context) => {
  const res = await fetch('http://localhost:3000/api/leagues')
  const data: Data = await res.json()
  return {
    props: {
      data,
    },
  }
}

const Home: NextPage = (props) => {
  const [leagues ,setLeagues] = useState<Data[] | null>( props.data.data);
  if (!leagues) {
    return <h1>sorry idiot you messed up</h1>
  }
  return (
    <>
      <Head>
        <title>Golf League Beta</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <>
        <h1 className="sm:text-4xl sm:flex sm:justify-center">Golf Leagues</h1>
        <div className="sm:flex sm:justify-center">
          <form action="">
            <label htmlFor="">
              League Name
            </label>
            <input type="text" className="border p-2 m-2" />
            <button className="border p-2">Search</button>
          </form>
        </div>
        <h3 className="sm:flex sm:justify-center sm:m-3">Leagues</h3>
        <div className="sm:h-1/2 sm:w-12/12 sm:flex sm:justify-center">
           <ul className="sm:flex sm:flex-col sm:justify-center">
            {
              leagues.map(league => (
                <div key={league.id}  className="sm:flex sm:justify-center">
                <Link key={league.id} href={`leagueHome/${league.name}?name=${league.name}&id=${league.id}`}>
              <li className="sm:flex sm:border sm:cursor-pointer sm:hover:bg-sky-700 sm:justify-center sm:m-3 sm:p-3" key={league.id}>
                League Name: {league.name} id: {league.id}</li>
                </Link>
                </div>
            )) }

              
           </ul>
           </div>
           <div className="sm:flex sm:justify-center ">
           <a href="/addTeam" className=" sm:hover:bg-sky-700 sm:btn sm:border sm:p-3 sm:flex sm:justify-center">Add League</a>
           </div>
          </>
      </main>
    </>
  );
};

export default Home;
