// this is the home page for an individual team
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from 'next/router';
import Link from 'next/link';
import { GetServerSideProps } from 'next'
import { useEffect, useState } from "react";


type Data = { 
  id:number;
  name:string;
 }

const playerHome: NextPage = (props) => {
  const router = useRouter()
  const playerId = router.query.id
  const playerName = router.query.name
  const [player,setPlayer] = useState([])
    
    //call to db for player info. TODO: optimize db for less calls
  useEffect(()=>{
    fetch(`/api/playerSearch/player/${playerId}`)
    .then((res)  =>  
      res.json()
    )
    .then((data) =>{ 
      console.log(data)
      setPlayer(data)
  },);  
  },[playerId])
  if (!player) {
    return <h1>Sorry we had a problem finding that player</h1>
  }
  //TODO: this needs to list the players on the selected team and link to there page
  return (
    <>
    <Head>
    <title> {playerName}</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main>
        <h1 className=" sm:m-2 sm:text-xl sm:flex sm:justify-center"> {playerName}</h1>
        <div className="sm:h-1/2 sm:w-12/12 sm:flex sm:justify-center">
                <div className="sm:flex sm:justify-center">
                  <img src="" alt="" />
                </div>            
          
           
           </div>

  </main>
        </>
  )
}

export default playerHome;