// this is the home page for an individual team
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from 'next/router';
import Link from 'next/link';
import { GetServerSideProps } from 'next'
import { useEffect, useState } from "react";

type Data = { 
  id:number;
  name:string;
 }

const teamHome: NextPage = (props) => {
  const router = useRouter()
  const teamId = router.query.id
  const teamName = router.query.name
  const [team,setTeam] = useState([])
  const [players,setPlayers] = useState([])
  //client side call to DB for team data
  useEffect(() => {
    if(teamId !== undefined){
      //team data
    fetch(`/api/teamSearch/${teamId}`)
    .then((res)  =>  
      res.json()
    )
    .then((data) =>{ 
      console.log(data)
      setTeam(data['team'])})
    
    //call to db for player info. TODO: optimize db for less calls
    fetch(`/api/playerSearch/${teamId}`)
    .then((res)  =>  
      res.json()
    )
    .then((data) =>{ 
      console.log(data)
      setPlayers(data['players'])})
    }

  },[teamId])  
  if (!team) {
    return <h1>sorry idiot</h1>
  }
  //TODO: this needs to list the players on the selected team and link to there page
  return (
    <>
    <Head>
    <title>Golf team {teamName}</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main>
        <h1 className=" sm:m-2 sm:text-lg sm:flex sm:justify-center"> {teamName} </h1>
        <div className="sm:h-1/2 sm:w-12/12 sm:flex sm:justify-center">
           <ul className="sm:flex sm:flex-col sm:justify-center">
                <div className="sm:flex sm:justify-center">
                <Link href={`/teamHome/${team.name}?name=${team.name}&id=${team.id}`}>
              <li className="sm:flex sm:border sm:cursor-pointer sm:hover:bg-sky-700 sm:justify-center sm:m-3 sm:p-3" key={team.id}>
                 Team: {team.name} id: {team.id}</li>
                </Link>
                </div>            
           </ul>
           </div>
           <div>
            <ul>
              {
              players.map(player=> (
                <div className="sm:flex sm:justify-center">
                  <Link href={`/playerHome/${player.name}?name=${player.name}&id=${player.id}`}>
                  <li>{player.name}</li>
                  </Link>
                </div>
              ))
              }
            </ul>
           </div>
  </main>
        </>
  )
}

export default teamHome;